name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  nox:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # ensure setuptools-scm can derive version from git

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install nox
        run: |
          python -m pip install --upgrade pip
          pip install nox

      - name: Run nox sessions
        run: |
          nox -s all

name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dev deps
        run: pip install .[dev]
      - name: Ruff
        run: ruff check .
      - name: Black
        run: black --check .
      - name: Mypy
        run: mypy tmiplus
      - name: Tests
        run: pytest -q
