name: Update README on Release

on:
  workflow_run:
    workflows: [ "Build and Release on Tag", ".github/workflows/release.yml" ]
    types: [ completed ]

permissions:
  contents: write

concurrency:
  group: update-readme-on-release
  cancel-in-progress: true

jobs:
  update-readme:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}

      - name: Resolve tag for this run
        id: tag
        run: |
          git fetch --tags --force --prune
          TAG=$(git tag --points-at "${{ github.event.workflow_run.head_sha }}")
          if [ -z "$TAG" ]; then
            echo "No tag points at ${{ github.event.workflow_run.head_sha }}"
            exit 1
          fi
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
          echo "Resolved TAG=$TAG"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Update README install command
        run: |
          python -m pip install --upgrade pip
          python scripts/update_readme_install.py "${{ steps.tag.outputs.tag }}"

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout ${{ github.event.repository.default_branch }}
          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git add README.md
          git commit -m "docs(README): update install command for ${{ steps.tag.outputs.tag }} [skip ci]"
          git push origin HEAD:${{ github.event.repository.default_branch }}
